import Foundation
import NetworkModelGenerator

enum PreviewData {
    static let meals: [Meal] = [
        .init(id: "53049", name: "Apam balik", thumnailURL: "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg"),
        .init(id: "52893", name: "Apple & Blackberry Crumble", thumnailURL: "https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg"),
        .init(id: "52768", name: "Apple Frangipan Tart", thumnailURL: "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg"),
        .init(id: "52767", name: "Bakewell tart", thumnailURL: "https://www.themealdb.com/images/media/meals/wyrqqq1468233628.jpg"),
        .init(id: "52855", name: "Banana Pancakes", thumnailURL: "https://www.themealdb.com/images/media/meals/sywswr1511383814.jpg"),
        .init(id: "52894", name: "Battenberg Cake", thumnailURL: "https://www.themealdb.com/images/media/meals/ywwrsp1511720277.jpg"),
        .init(id: "52928", name: "BeaverTails", thumnailURL: "https://www.themealdb.com/images/media/meals/ryppsv1511815505.jpg"),
        .init(id: "52891", name: "Blackberry Fool", thumnailURL: "https://www.themealdb.com/images/media/meals/rpvptu1511641092.jpg"),
        .init(id: "52792", name: "Bread and Butter Pudding", thumnailURL: "https://www.themealdb.com/images/media/meals/xqwwpy1483908697.jpg"),
        .init(id: "52961", name: "Budino Di Ricotta", thumnailURL: "https://www.themealdb.com/images/media/meals/1549542877.jpg"),
        .init(id: "52923", name: "Canadian Butter Tarts", thumnailURL: "https://www.themealdb.com/images/media/meals/wpputp1511812960.jpg"),
        .init(id: "52897", name: "Carrot Cake", thumnailURL: "https://www.themealdb.com/images/media/meals/vrspxv1511722107.jpg"),
        .init(id: "52976", name: "Cashew Ghoriba Biscuits", thumnailURL: "https://www.themealdb.com/images/media/meals/t3r3ka1560461972.jpg"),
        .init(id: "52898", name: "Chelsea Buns", thumnailURL: "https://www.themealdb.com/images/media/meals/vqpwrv1511723001.jpg"),
        .init(id: "52910", name: "Chinon Apple Tarts", thumnailURL: "https://www.themealdb.com/images/media/meals/qtqwwu1511792650.jpg"),
        .init(id: "52856", name: "Choc Chip Pecan Pie", thumnailURL: "https://www.themealdb.com/images/media/meals/rqvwxt1511384809.jpg"),
        .init(id: "52853", name: "Chocolate Avocado Mousse", thumnailURL: "https://www.themealdb.com/images/media/meals/uttuxy1511382180.jpg"),
        .init(id: "52966", name: "Chocolate Caramel Crispy", thumnailURL: "https://www.themealdb.com/images/media/meals/1550442508.jpg"),
        .init(id: "52776", name: "Chocolate Gateau", thumnailURL: "https://www.themealdb.com/images/media/meals/tqtywx1468317395.jpg"),
        .init(id: "52860", name: "Chocolate Raspberry Brownies", thumnailURL: "https://www.themealdb.com/images/media/meals/yypvst1511386427.jpg"),
        .init(id: "52905", name: "Chocolate Souffle", thumnailURL: "https://www.themealdb.com/images/media/meals/twspvx1511784937.jpg"),
        .init(id: "52990", name: "Christmas cake", thumnailURL: "https://www.themealdb.com/images/media/meals/ldnrm91576791881.jpg"),
        .init(id: "52788", name: "Christmas Pudding Flapjack", thumnailURL: "https://www.themealdb.com/images/media/meals/vvusxs1483907034.jpg"),
        .init(id: "52989", name: "Christmas Pudding Trifle", thumnailURL: "https://www.themealdb.com/images/media/meals/r33cud1576791081.jpg"),
        .init(id: "52988", name: "Classic Christmas pudding", thumnailURL: "https://www.themealdb.com/images/media/meals/1d85821576790598.jpg"),
        .init(id: "52899", name: "Dundee cake", thumnailURL: "https://www.themealdb.com/images/media/meals/wxyvqq1511723401.jpg"),
        .init(id: "52888", name: "Eccles Cakes", thumnailURL: "https://www.themealdb.com/images/media/meals/wtqrqw1511639627.jpg"),
        .init(id: "52791", name: "Eton Mess", thumnailURL: "https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg"),
        .init(id: "53007", name: "Honey Yogurt Cheesecake", thumnailURL: "https://www.themealdb.com/images/media/meals/y2irzl1585563479.jpg"),
        .init(id: "52787", name: "Hot Chocolate Fudge", thumnailURL: "https://www.themealdb.com/images/media/meals/xrysxr1483568462.jpg"),
        .init(id: "52890", name: "Jam Roly-Poly", thumnailURL: "https://www.themealdb.com/images/media/meals/ysqupp1511640538.jpg"),
        .init(id: "52859", name: "Key Lime Pie", thumnailURL: "https://www.themealdb.com/images/media/meals/qpqtuu1511386216.jpg"),
        .init(id: "53015", name: "Krispy Kreme Donut", thumnailURL: "https://www.themealdb.com/images/media/meals/4i5cnx1587672171.jpg"),
        .init(id: "52900", name: "Madeira Cake", thumnailURL: "https://www.themealdb.com/images/media/meals/urtqut1511723591.jpg"),
        .init(id: "52991", name: "Mince Pies", thumnailURL: "https://www.themealdb.com/images/media/meals/qe8pf51576795532.jpg"),
        .init(id: "52924", name: "Nanaimo Bars", thumnailURL: "https://www.themealdb.com/images/media/meals/vwuprt1511813703.jpg"),
        .init(id: "52858", name: "New York cheesecake", thumnailURL: "https://www.themealdb.com/images/media/meals/swttys1511385853.jpg"),
        .init(id: "52854", name: "Pancakes", thumnailURL: "https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg"),
        .init(id: "52902", name: "Parkin Cake", thumnailURL: "https://www.themealdb.com/images/media/meals/qxuqtt1511724269.jpg"),
        .init(id: "52862", name: "Peach & Blueberry Grunt", thumnailURL: "https://www.themealdb.com/images/media/meals/ssxvup1511387476.jpg"),
        .init(id: "52861", name: "Peanut Butter Cheesecake", thumnailURL: "https://www.themealdb.com/images/media/meals/qtuuys1511387068.jpg"),
        .init(id: "52958", name: "Peanut Butter Cookies", thumnailURL: "https://www.themealdb.com/images/media/meals/1544384070.jpg"),
        .init(id: "52916", name: "Pear Tarte Tatin", thumnailURL: "https://www.themealdb.com/images/media/meals/rxvxrr1511797671.jpg"),
        .init(id: "53022", name: "Polskie Naleśniki (Polish Pancakes)", thumnailURL: "https://www.themealdb.com/images/media/meals/58bkyo1593350017.jpg"),
        .init(id: "53046", name: "Portuguese custard tarts", thumnailURL: "https://www.themealdb.com/images/media/meals/vmz7gl1614350221.jpg"),
        .init(id: "52932", name: "Pouding chomeur", thumnailURL: "https://www.themealdb.com/images/media/meals/yqqqwu1511816912.jpg"),
        .init(id: "52857", name: "Pumpkin Pie", thumnailURL: "https://www.themealdb.com/images/media/meals/usuqtp1511385394.jpg"),
        .init(id: "52901", name: "Rock Cakes", thumnailURL: "https://www.themealdb.com/images/media/meals/tqrrsq1511723764.jpg"),
        .init(id: "52786", name: "Rocky Road Fudge", thumnailURL: "https://www.themealdb.com/images/media/meals/vtxyxv1483567157.jpg"),
        .init(id: "53024", name: "Rogaliki (Polish Croissant Cookies)", thumnailURL: "https://www.themealdb.com/images/media/meals/7mxnzz1593350801.jpg"),
        .init(id: "52833", name: "Salted Caramel Cheescake", thumnailURL: "https://www.themealdb.com/images/media/meals/xqrwyr1511133646.jpg"),
        .init(id: "53054", name: "Seri muka kuih", thumnailURL: "https://www.themealdb.com/images/media/meals/6ut2og1619790195.jpg"),
        .init(id: "52886", name: "Spotted Dick", thumnailURL: "https://www.themealdb.com/images/media/meals/xqvyqr1511638875.jpg"),
        .init(id: "52883", name: "Sticky Toffee Pudding", thumnailURL: "https://www.themealdb.com/images/media/meals/xqqqtu1511637379.jpg"),
        .init(id: "52793", name: "Sticky Toffee Pudding Ultimate", thumnailURL: "https://www.themealdb.com/images/media/meals/xrptpq1483909204.jpg"),
        .init(id: "53005", name: "Strawberry Rhubarb Pie", thumnailURL: "https://www.themealdb.com/images/media/meals/178z5o1585514569.jpg"),
        .init(id: "52931", name: "Sugar Pie", thumnailURL: "https://www.themealdb.com/images/media/meals/yrstur1511816601.jpg"),
        .init(id: "52889", name: "Summer Pudding", thumnailURL: "https://www.themealdb.com/images/media/meals/rsqwus1511640214.jpg"),
        .init(id: "52909", name: "Tarte Tatin", thumnailURL: "https://www.themealdb.com/images/media/meals/ryspuw1511786688.jpg"),
        .init(id: "52929", name: "Timbits", thumnailURL: "https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg"),
        .init(id: "52892", name: "Treacle Tart", thumnailURL: "https://www.themealdb.com/images/media/meals/wprvrw1511641295.jpg"),
        .init(id: "52970", name: "Tunisian Orange Cake", thumnailURL: "https://www.themealdb.com/images/media/meals/y4jpgq1560459207.jpg"),
        .init(id: "53062", name: "Walnut Roll Gužvara", thumnailURL: "https://www.themealdb.com/images/media/meals/u9l7k81628771647.jpg"),
        .init(id: "52917", name: "White chocolate creme brulee", thumnailURL: "https://www.themealdb.com/images/media/meals/uryqru1511798039.jpg")
    ]
    
    static let mealDetails: MealDetail = .init(
        id: "52832",
        name: "Coq au vin",
        thumnailURL: "https://www.themealdb.com/images/media/meals/qstyvs1505931190.jpg",
        categoryName: "Chicken",
        originName: "French",
        instructions: "Heat 1 tbsp of the oil in a large, heavy-based saucepan or flameproof dish. Tip in the bacon and fry until crisp. Remove and drain on kitchen paper. Add the shallots to the pan and fry, stirring or shaking the pan often, for 5-8 mins until well browned all over. Remove and set aside with the bacon.\r\nPat the chicken pieces dry with kitchen paper. Pour the remaining oil into the pan, then fry half the chicken pieces, turning regularly, for 5-8 mins until well browned. Remove, then repeat with the remaining chicken. Remove and set aside.\r\nScatter in the garlic and fry briefly, then, with the heat medium-high, pour in the brandy or Cognac, stirring the bottom of the pan to deglaze. The alcohol should sizzle and start to evaporate so there is not much left.\r\nReturn the chicken legs and thighs to the pan along with any juices, then pour in a little of the wine, stirring the bottom of the pan again. Stir in the rest of the wine, the stock and tomato purée, drop in the bouquet garni, season with pepper and a pinch of salt, then return the bacon and shallots to the pan. Cover, lower the heat to a gentle simmer, add the chicken breasts and cook for 50 mins-1hr.\r\nJust before ready to serve, heat the oil for the mushrooms in a large non-stick frying pan. Add the mushrooms and fry over a high heat for a few mins until golden. Remove and keep warm.\r\nLift the chicken, shallots and bacon from the pan and transfer to a warmed serving dish. Remove the bouquet garni. To make the thickener, mix the flour, olive oil and butter in a small bowl using the back of a teaspoon. Bring the wine mixture to a gentle boil, then gradually drop in small pieces of the thickener, whisking each piece in using a wire whisk. Simmer for 1-2 mins. Scatter the mushrooms over the chicken, then pour over the wine sauce. Garnish with chopped parsley.",
        ingredientMeasures: [
            .init(name: "Olive Oil", measure: "1½ tbsp"),
            .init(name: "Bacon", measure: "3 rashers (100g) chopped dry-cured"),
            .init(name: "Shallots", measure: "12 small"),
            .init(name: "Chicken Legs", measure: "2 (460g)"),
            .init(name: "Chicken Thighs", measure: "4 (650g)"),
            .init(name: "Chicken Breasts", measure: "2 (280g)"),
            .init(name: "Garlic", measure: "3 finely chopped"),
            .init(name: "Brandy", measure: "3 tbsp"),
            .init(name: "Red Wine", measure: "600ml"),
            .init(name: "Chicken Stock", measure: "150ml"),
            .init(name: "tomato puree", measure: "2 tsp"),
            .init(name: "thyme", measure: "3 sprigs"),
            .init(name: "Rosemary", measure: "2 sprigs"),
            .init(name: "bay leaves", measure: "2"),
            .init(name: "parsley", measure: "garnish"),
            .init(name: "chestnut mushroom", measure: "250g"),
            .init(name: "plain flour", measure: "2 tbsp"),
            .init(name: "butter", measure: "1 tsp")
        ],
        tags: ["Tastes-like-chicken", "Vampire Defense"],
        youtubeURL: "https://www.youtube.com/watch?v=_ise46LADBs",
        sourceURL: "https://www.bbcgoodfood.com/recipes/1913655/coq-au-vin"
    )
    
}

    

